### ISSUE TITLE
fails silently with no test relative path set in execution parameters

### ISSUE THREAD

**Issue by icemachined** [saveourtool/save-cloud#864] opened 2022-06-29 14:10 UTC
if you don't set relative path, backend fails with exception silently

```
17:03:28.277 [parallel-10] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [46c6edfa-10]  500 Server Error for HTTP GET "/api/v1/getTestRootPathByExecutionId?id=33"
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:608)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler com.saveourtool.save.backend.controllers.ExecutionController#getTestRootPathByExecutionId(long, Authentication) [DispatcherHandler]
```

**Comment by petertrr** [comment] 2022-06-29 14:27
Duplicate of #850?

**Closed** 2022-07-05 14:32 UTC
Labels: duplicate
