### ISSUE TITLE
Support the logic of deleting contests

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1135] opened 2022-09-01 22:15 UTC
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/58667063/188022147-d1de10a4-6cd0-404b-9407-d41893f072e9.png">

We can add a new contest, but cannot delete them

**Comment by akuleshov7** [comment] 2022-09-01 22:15
urgent

**Comment by 0x6675636b796f75676974687562** [comment] 2022-10-17 11:46
Closing as a duplicate of #1036.

**Closed by 0x6675636b796f75676974687562** 2022-10-17 11:46 UTC
